[package]
name = "ewanophobia/rapbattles"
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = []

[dependencies]
Knit = "sleitnick/knit@1.4.4"
Comm = "sleitnick/comm@^0.1.2"
Promise = "evaera/promise@^3.1.0"
Janitor = "howmanysmall/janitor@^1.13.15"
TableUtil = "sleitnick/table-util@1.1.1"
ColourUtils = "csqrl/colour-utils@^1.1.0"
signal = "sleitnick/signal@1.1.0"

[dev-dependencies]
TestEZ = "roblox/testez@^0.4.1"
