name: CD
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Once per day at 00:00 UTC
  push:
    branches:
      - main

jobs:
  cd:
    name: Integration Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Foreman
      run: foreman install

    - name: Run Wally
      run: wally install


    - name: Deploy
      run: rojo upload --cookie "$ROBLOSECURITY" --asset_id 9141286177
      env:
        ROBLOSECURITY: ${{ secrets.CD_ROBLOSECURITY }}

