name: CD
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Once per day at 00:00 UTC
  push:
    branches:
      - main

jobs:
  cd:
    name: Integration Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Foreman
      run: foreman install

    - name: Run Wally
      run: wally install


    - name: Build
      run: rojo build -o "game.rbxlx"

    - name: Deploy
      uses: wei/curl@v1
      with:
        args: --verbose --location --request POST 'https://apis.roblox.com/universes/v1/3432515351/places/9141286177/versions?versionType=Published' --header 'x-api-key: $WRITE_API_KEY' --header 'Content-Type: application/xml' -d ./game.rbxlx {"versionNumber":9}
        env:
          WRITE_API_KEY: ${{ secrets.WRITE_API_KEY }}

